#!/usr/bin/env python3
"""Keep the `<link rel="modulepreload">` block in console/frontend/index.html exact.

The page's ES-module graph (workspace.js -> the vendored Vela, vela-pinets, PineTS and ~140 small Zag /
floating-ui files) is found one level at a time by the browser: each file has to arrive and be read before the
files IT imports are even requested. Measured 6 Oct: 17 sequential waves, about 1.3 s of a 1.8 s boot. Listing the
whole graph up front lets the browser fetch it in parallel (first canvas 1,792 ms -> 1,501 ms, median of 5,
localhost).

The list is derived, never typed: this script walks the static `import ... from "x"`, `export ... from "x"`,
`import "x"` and `import("x")` string specifiers from workspace.js, resolves bare ones through the page's import
map, and prints / writes the block. The test suite runs `--check`, so a vendor upgrade that changes the graph fails
there instead of silently leaving a stale list.

  tools/modulepreload.py            print the block
  tools/modulepreload.py --write    rewrite it in index.html
  tools/modulepreload.py --check    exit 1 when index.html's block is not exactly this
"""
import json
import re
import sys
from pathlib import Path

FRONT = Path(__file__).resolve().parent.parent / "console" / "frontend"
INDEX = FRONT / "index.html"
ENTRY = "workspace.js"
START = "<!-- modulepreload:start (generated by tools/modulepreload.py - do not edit by hand) -->"
END = "<!-- modulepreload:end -->"

# `from "x"`, `from'x'`, `import "x"`, `import"x"`, `import("x")`, `import('x')` — also in minified code
SPECIFIER = re.compile(r"""(?:\bfrom\s*|\bimport\s*\(?\s*)(["'])([^"'\n]+)\1""")


def import_map() -> dict:
    m = re.search(r'<script type="importmap">(.*?)</script>', INDEX.read_text(), re.S)
    return json.loads(m.group(1))["imports"] if m else {}


def resolve(spec: str, importer: Path, imports: dict):
    if re.match(r"^[a-z]+:", spec):
        return None                                          # a URL: not ours to preload
    if spec.startswith((".", "/")):
        target = (importer.parent / spec).resolve() if spec.startswith(".") else (FRONT / spec.lstrip("/")).resolve()
    elif spec in imports:
        target = (FRONT / imports[spec]).resolve()
    else:
        return None                                          # a bare name the map does not know
    return target if target.is_file() and FRONT.resolve() in target.parents else None


def graph() -> list:
    imports = import_map()
    entry = (FRONT / ENTRY).resolve()
    seen, order, todo = set(), [], [entry]
    while todo:
        f = todo.pop()
        if f in seen:
            continue
        seen.add(f)
        if f != entry:                                       # (vendor/vela/dist/workspace.js is a different file)
            order.append(f)
        if f.suffix not in (".js", ".mjs"):
            continue
        for _q, spec in SPECIFIER.findall(f.read_text(errors="replace")):
            t = resolve(spec, f, imports)
            if t is not None and t not in seen:
                todo.append(t)
    return sorted("./" + p.relative_to(FRONT.resolve()).as_posix() for p in order)


def block() -> str:
    return "\n".join([START] + [f'<link rel="modulepreload" href="{h}">' for h in graph()] + [END])


def current(html: str):
    m = re.search(re.escape(START) + r".*?" + re.escape(END), html, re.S)
    return m.group(0) if m else None


def main(argv) -> int:
    want = block()
    html = INDEX.read_text()
    have = current(html)
    if "--check" in argv:
        if have == want:
            return 0
        print("index.html's modulepreload block is stale: run tools/modulepreload.py --write", file=sys.stderr)
        return 1
    if "--write" in argv:
        if have is None:
            print("no modulepreload block in index.html (add the start / end markers first)", file=sys.stderr)
            return 1
        INDEX.write_text(html.replace(have, want))
        print(f"wrote {want.count('<link')} modulepreload links")
        return 0
    print(want)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
